### ISSUE TITLE
.pic

### ISSUE THREAD

**Issue by rhaul** [ogamespec/PicDecoder#1]
hello.

I'm not a programmer, how do you start this program?
I have windows 10.

**Comment by ogamespec** [comment]
Try https://github.com/ogamespec/PicDecoder/releases/tag/picdecoder-10

**Comment by rhaul** [comment]
I'm sorry I don't understand much about programming.

The program PicDecord 10 does not open the .pic files of the pc game "Darklands", they are very old files and maybe that is why (1992).

**Comment by ogamespec** [comment]
I only checked on Magic the Gathering, I haven't looked at the others.

**Comment by rhaul** [comment]
Ok, thanks
Could you make another one for darklands?

**Comment by ogamespec** [comment]
I don't have an opportunity right now, maybe someone else can. Well, or you learn programming and do it - it will be a good motivation.

**Comment by rhaul** [comment]
ok. Thanks
